### PR TITLE
Updating docs for configuring plugin

### PR DESCRIPTION
**Pull request by SpencerKaiser**
Modified the docs with slightly clearer instructions, replaced `1, 2, 3` numbering to make future updates easier (you don't need to renumber when adding a step in the middle)

Also added a comment about the need for a static IP address

Let me know if you have any feedback

### CODE REVIEW

**Comment by karlvr** [comment]
@SpencerKaiser thank you very much for this PR. That's an interesting point about your Roomba and its IP address. I don't think my Roomba has a static IP... it's just managed to retain its IP address lease I guess. Have you had a problem with your Roomba's IP address changing?

**Comment by SpencerKaiser** [comment]
> Have you had a problem with your Roomba's IP address changing?
No but I just figured this would be an issue... if not, you have some magic on your end for how you communicate with the Roomba after a router restart 🤔 I also saw #36 which sounded like the same issue.

Let me take another pass at formatting based on your feedback and you can let me know what you think 😉

**Comment by SpencerKaiser** [comment]
Ah, never mind... looks like you already made my other changes in another PR ☹️

**Comment by karlvr** [comment]
@SpencerKaiser I have made some large changes in the last couple of days, but I haven't incorporated anything about static IP addresses, or anything about IP addresses at all I think... I do think that a troubleshooting section would be useful, and an instruction to check the IP would be valuable if you feel like adapting what you've written to go there?

**Pull request closed without merging**
